import type { Question, Category, KeywordData, TrafficData } from '../types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Kayıt İşlemleri', questionCount: 45 },
  { id: '2', name: 'Ders Seçimi', questionCount: 32 },
  { id: '3', name: 'Yurt ve Barınma', questionCount: 28 },
  { id: '4', name: 'Sınavlar ve Notlar', questionCount: 50 },
  { id: '5', name: 'Burs Olanakları', questionCount: 15 },
];

export const mockQuestions: Question[] = [
  {
    id: '101',
    text: 'Ders kayıt tarihleri ne zaman başlıyor?',
    authorId: 'u1',
    authorName: 'Ahmet Yılmaz',
    authorFaculty: 'Mühendislik Fakültesi',
    authorDepartment: 'Bilgisayar Mühendisliği',
    status: 'answered',
    favorites: 120,
    createdAt: '2026-05-01T10:00:00Z',
    categoryId: '2',
    answer: 'Ders kayıtları Akademik Takvimde belirtildiği üzere 15 Eylül - 20 Eylül tarihleri arasında yapılacaktır. OBS (Öğrenci Bilgi Sistemi) üzerinden işlemlerinizi tamamlayabilirsiniz.',
  },
  {
    id: '102',
    text: 'Yaz okulu açılacak mı?',
    authorId: 'u2',
    authorName: 'Ayşe Demir',
    authorFaculty: 'Eğitim Fakültesi',
    authorDepartment: 'Sınıf Öğretmenliği',
    status: 'answered',
    favorites: 85,
    createdAt: '2026-04-28T14:30:00Z',
    categoryId: '4',
    answer: 'Evet, yaz okulu başvuruları Haziran ayının ilk haftası başlayacaktır. İlgili derslerin listesi fakülte panolarında ve web sitemizde duyurulacaktır.',
  },
  {
    id: '103',
    text: 'KYK yurdu başvuruları nasıl yapılıyor?',
    authorId: 'u3',
    authorName: 'Mehmet Kaya',
    authorFaculty: 'İktisadi ve İdari Bilimler Fakültesi',
    authorDepartment: 'İşletme',
    status: 'answered',
    favorites: 210,
    createdAt: '2026-04-15T09:15:00Z',
    categoryId: '3',
    answer: 'KYK yurt başvuruları e-Devlet üzerinden Gençlik ve Spor Bakanlığı hizmetleri altından belirtilen tarihlerde yapılmaktadır. Üniversitemizin doğrudan yurt kaydı alma yetkisi yoktur.',
  },
  {
    id: '104',
    text: 'Dondurma işlemi için hangi belgelere ihtiyacım var?',
    authorId: 'u1',
    authorName: 'Ahmet Yılmaz',
    authorFaculty: 'Mühendislik Fakültesi',
    authorDepartment: 'Bilgisayar Mühendisliği',
    status: 'pending',
    favorites: 15,
    createdAt: '2026-05-02T11:20:00Z',
    isFavoritedByMe: true,
  },
  {
    id: '105',
    text: 'Yatay geçiş şartları nelerdir ortalama kaç olmalı?',
    authorId: 'u4',
    authorName: 'Fatma Şahin',
    authorFaculty: 'Fen Edebiyat Fakültesi',
    authorDepartment: 'Matematik',
    status: 'pending',
    favorites: 45,
    createdAt: '2026-05-02T12:00:00Z',
  },
  {
    id: '106',
    text: 'Erasmus sınavına kimler girebilir?',
    authorId: 'u2',
    authorName: 'Ayşe Demir',
    authorFaculty: 'Eğitim Fakültesi',
    authorDepartment: 'Sınıf Öğretmenliği',
    status: 'pending',
    favorites: 8,
    createdAt: '2026-05-01T16:45:00Z',
  },
  {
    id: '107',
    text: 'Bahar dönemi final tarihleri değişecek mi?',
    authorId: 'u5',
    authorName: 'Ali Can',
    authorFaculty: 'Spor Bilimleri Fakültesi',
    authorDepartment: 'Antrenörlük',
    status: 'rejected',
    favorites: 2,
    createdAt: '2026-04-20T10:00:00Z',
  }
];

export const mockKeywordData: KeywordData[] = [
  { name: 'Kayıt', value: 400 },
  { name: 'Sınav', value: 300 },
  { name: 'Yurt', value: 300 },
  { name: 'Ders', value: 200 },
  { name: 'Erasmus', value: 100 },
];

export const mockTrafficData: TrafficData[] = [
  { day: 'Pzt', questions: 24 },
  { day: 'Sal', questions: 35 },
  { day: 'Çar', questions: 18 },
  { day: 'Per', questions: 42 },
  { day: 'Cum', questions: 50 },
  { day: 'Cmt', questions: 15 },
  { day: 'Paz', questions: 10 },
];
